name = "yew-ssr-wrangler-demo"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "cargo install worker-build && cargo install trunk && trunk build && worker-build --release"